app1/urls.py
from app1.views import *

from django.urls import path

app_name ="something"

urlpatterns =[

    path('dulquar/',dulquar,name='dulquar'),
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name= "everything"

urlpatterns =[

    path('sahi/',sahi,name='sahi'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def dulquar(request):
    return render(request,'dulquar.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def sahi(request):

    return render(request,'sahi.html')

templates/dulquar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>HIII SAHIIII</h1>
        <h1>WHERE ARE YOU</h1>
        <h1>I HAVE BEEN WAITING FOR YOU HERE..Iam Longing to see you</h1>
        <h2><a href= "{%  url 'everything:sahi' %}">Navigate to sahi</h2></a>
    </center>
</body>
</html>

templates/sahi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>HIII DULQUAR</h1>
        <h1>IAM  AT HOME </h1>
        <h1> GIVE ME 10 MINI WILL BE THERE DEAR.... </h1>
        <h2><a href ="{%  url 'something:dulquar' %}" >NAVIGATE TO DULQUAR</a></h2>
    </center>
</body>
</html>